---
when:
  - event: [ push , manual ]
    branch: main
  - event: [ pull_request ]

steps:
  - image: woodpeckerci/plugin-docker-buildx:latest
    name: dryrun
    settings:
# renovate: datasource=github-releases depName=Kozea/Radicale
      tag: 3.5.1
      dockerfile: Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: linux/amd64
      pull_image: false
      repo: opencloudeu/radicale,quay.io/opencloudeu/radicale
    when:
      - event: pull_request
