---
when:
  - event: [ push , manual ]
    branch: main
  - event: [ pull_request ]

steps:
  - image: woodpeckerci/plugin-docker-buildx:latest
    name: dryrun
    settings:
# renovate: datasource=github-releases depName=Kozea/Radicale
      tags:
        - 3.5.2
        - latest
      dockerfile: Dockerfile
      dry_run: true
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: linux/amd64
      pull_image: false
      repo: opencloudeu/radicale,quay.io/opencloudeu/radicale
    when:
      - event: pull_request
  
  - image: woodpeckerci/plugin-docker-buildx:latest
    name: build-and-push
    settings:
# renovate: datasource=github-releases depName=Kozea/Radicale
      tags:
        - 3.5.2
        - latest
      dockerfile: Dockerfile
      http_proxy:
        from_secret: ci_http_proxy
      https_proxy:
        from_secret: ci_http_proxy
      platforms: linux/amd64
      pull_image: false
      logins:
        - registry: https://index.docker.io/v1/
          username:
            from_secret: docker_username
          password:
            from_secret: docker_password
        - registry: https://quay.io
          username:
            from_secret: quay_username
          password:
            from_secret: quay_password
      repo: opencloudeu/radicale,quay.io/opencloudeu/radicale
    when:
      - event: [ push , manual ]
        branch: main
